test = {   'name': 'q2_2',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(sd_outbreaks, bpd.DataFrame)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sd_outbreaks.shape == (844, 10)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> 'city' in sd_outbreaks.columns and 'street_address' in sd_outbreaks.columns and 'zip_code' in sd_outbreaks.columns # check column names\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
