test = {   'name': 'q2_8',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(outbreak_locations, bpd.DataFrame) and outbreak_locations.shape[1] == 7\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> outbreak_locations.shape[0] == 729 #there should be 729 unique outbreak locations - fix your mistake before proceeding\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
